In [1]:
import numpy as np

In [2]:
import array as arr

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

In [4]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
arr=np.array(([1,2,3],[4,5,6]))

In [10]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
arr=np.array(([1,2,3],
              [4,5,6],
              [7,8,9]))

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr=np.array(([1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]))

In [17]:
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
arr=np.array(([1,2,3],
              [2.2,2.4,2.6],
              ['pandas','numpy','matplotlib','seaborn','sklearn']))

<ipython-input-18-f10e8dffd0c1>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array(([1,2,3],


In [19]:
print(type(arr))

<class 'numpy.ndarray'>


In [20]:
arr=np.array(([1,2,3,'sreeram','Technologies','2+4j']))

In [21]:
print(arr)

['1' '2' '3' 'sreeram' 'Technologies' '2+4j']


In [22]:
print(type(arr))

<class 'numpy.ndarray'>


In [24]:
arr=np.array(([2,4,6],
              [2.1,2.2,2.4],
              ['python','Datascience','machinelearning','deeplearning','nlp','computer vision','nlp']
              ))
print(arr)

[list([2, 4, 6]) list([2.1, 2.2, 2.4])
 list(['python', 'Datascience', 'machinelearning', 'deeplearning', 'nlp', 'computer vision', 'nlp'])]


<ipython-input-24-01967a1b85df>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array(([2,4,6],


In [32]:
import array as arr
import numpy as np
arr=np.array([1,2,3], ndmin=1)

In [38]:
print(arr)

[1 2 3]


In [40]:
arr=np.array([1,2,3],dtype=complex)

In [41]:
print(arr)

[1.+0.j 2.+0.j 3.+0.j]


In [42]:
arr=np.array([1,2,3],dtype=float)

In [43]:
print(arr)

[1. 2. 3.]


In [44]:
arr=np.array([1,2,3],dtype=str)

In [45]:
print(arr)

['1' '2' '3']
